### ISSUE TITLE
yarn dev時にWarning: Failed prop type: Material-UI: This elevation `4` is not implemented.が出力される

### ISSUE THREAD

**Issue by d11j** [happou31/marine_button#79]
yarn devして一発目のアクセス時に以下の警告が出力される。
見た目、機能には影響が無さそう。

> Warning: Failed prop type: Material-UI: This elevation \`4\` is not implemented.
>     at Paper (/mnt/d/Project/marine_button/node_modules/@material-ui/core/Paper/Paper.js:55:23)
>     at WithStyles (/mnt/d/Project/marine_button/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
>     at AppBar (/mnt/d/Project/marine_button/node_modules/@material-ui/core/AppBar/AppBar.js:114:23)
>     at WithStyles (/mnt/d/Project/marine_button/node_modules/@material-ui/styles/withStyles/withStyles.js:67:31)
>     at exports.modules../src/container/FooterContainer/FooterContainer.tsx.__webpack_exports__.default (/mnt/d/Project/marine_button/.next/server/pages/index.js:2822:70)
>     at exports.modules../pages/index.tsx.__webpack_exports__.default (/mnt/d/Project/marine_button/.next/server/pages/index.js:2126:76)
>     at Provider (/mnt/d/Project/marine_button/node_modules/react-redux/lib/components/Provider.js:21:20)
>     at StylesProvider (/mnt/d/Project/marine_button/node_modules/@material-ui/styles/StylesProvider/StylesProvider.js:57:24)
>     at ThemeProvider (/mnt/d/Project/marine_button/node_modules/@material-ui/styles/ThemeProvider/ThemeProvider.js:48:24)
>     at exports.modules../pages/_app.tsx.__webpack_exports__.default (/mnt/d/Project/marine_button/.next/server/pages/_app.js:56:3)
>     at AppContainer (/mnt/d/Project/marine_button/node_modules/next/dist/next-server/server/render.js:27:952)

**Comment by d11j** [comment]
もう出力されないので解決
